export const mockPatients = [
  {
    id: "p1",
    name: "James Holloway",
    email: "james.h@email.com",
    phone: "+1 (555) 234-5678",
    ssn: "***-**-4521",
    dob: "1988-03-15",
    address: "742 Evergreen Terrace, Springfield, IL",
    diagnosis: "Generalized Anxiety Disorder",
    therapist: "Dr. Sarah Mitchell",
    status: "active" as const,
    nextSession: "2026-03-15 10:00 AM",
    sessions: 12,
    insurance: "BlueCross PPO",
    emergencyContact: "Linda Holloway - +1 (555) 876-5432",
    notes: "Responding well to CBT. Reduce session frequency next month.",
  },
  {
    id: "p2",
    name: "Maria Santos",
    email: "maria.s@email.com",
    phone: "+1 (555) 345-6789",
    ssn: "***-**-7832",
    dob: "1995-07-22",
    address: "1201 Oak Ave, Portland, OR",
    diagnosis: "Major Depressive Disorder",
    therapist: "Dr. Sarah Mitchell",
    status: "active" as const,
    nextSession: "2026-03-14 2:00 PM",
    sessions: 8,
    insurance: "Aetna HMO",
    emergencyContact: "Carlos Santos - +1 (555) 654-3210",
    notes: "Started SSRI medication. Monitor progress.",
  },
  {
    id: "p3",
    name: "Robert Kim",
    email: "robert.k@email.com",
    phone: "+1 (555) 456-7890",
    ssn: "***-**-1234",
    dob: "1979-11-08",
    address: "330 Pine St, Seattle, WA",
    diagnosis: "PTSD",
    therapist: "Dr. Amara Johnson",
    status: "inactive" as const,
    nextSession: "—",
    sessions: 24,
    insurance: "United Healthcare",
    emergencyContact: "Susan Kim - +1 (555) 321-0987",
    notes: "Completed treatment plan. Follow-up in 3 months.",
  },
  {
    id: "p4",
    name: "Emily Chen",
    email: "emily.c@email.com",
    phone: "+1 (555) 567-8901",
    ssn: "***-**-5678",
    dob: "2001-01-30",
    address: "55 Maple Dr, Austin, TX",
    diagnosis: "Social Anxiety Disorder",
    therapist: "Dr. Sarah Mitchell",
    status: "active" as const,
    nextSession: "2026-03-16 11:00 AM",
    sessions: 5,
    insurance: "Cigna",
    emergencyContact: "Wei Chen - +1 (555) 210-9876",
    notes: "New patient. Establishing rapport.",
  },
];

export const mockTherapists = [
  { id: "t1", name: "Dr. Sarah Mitchell", specialty: "CBT, Anxiety", patients: 18, rating: 4.9, status: "online" as const },
  { id: "t2", name: "Dr. Amara Johnson", specialty: "PTSD, Trauma", patients: 14, rating: 4.8, status: "busy" as const },
  { id: "t3", name: "Dr. Michael Torres", specialty: "Depression, Couples", patients: 22, rating: 4.7, status: "online" as const },
  { id: "t4", name: "Dr. Lisa Park", specialty: "Child Psychology", patients: 16, rating: 4.9, status: "offline" as const },
];

export const mockFinancials = {
  totalRevenue: 284500,
  monthlyRevenue: 42300,
  outstandingPayments: 12800,
  avgSessionRate: 185,
  revenueByMonth: [
    { month: "Oct", revenue: 38200 },
    { month: "Nov", revenue: 41500 },
    { month: "Dec", revenue: 35800 },
    { month: "Jan", revenue: 43200 },
    { month: "Feb", revenue: 40800 },
    { month: "Mar", revenue: 42300 },
  ],
};

export const mockSessions = [
  { id: "s1", patient: "James Holloway", therapist: "Dr. Sarah Mitchell", date: "2026-03-15 10:00 AM", type: "Video", status: "scheduled" },
  { id: "s2", patient: "Maria Santos", therapist: "Dr. Sarah Mitchell", date: "2026-03-14 2:00 PM", type: "Chat", status: "scheduled" },
  { id: "s3", patient: "Emily Chen", therapist: "Dr. Sarah Mitchell", date: "2026-03-16 11:00 AM", type: "Video", status: "scheduled" },
  { id: "s4", patient: "Robert Kim", therapist: "Dr. Amara Johnson", date: "2026-03-10 9:00 AM", type: "Video", status: "completed" },
];

export const mockMessages = [
  { id: "m1", from: "James Holloway", message: "Thank you for today's session, it was really helpful.", time: "2 hours ago", unread: true },
  { id: "m2", from: "Maria Santos", message: "Can we reschedule Thursday's session?", time: "5 hours ago", unread: true },
  { id: "m3", from: "Emily Chen", message: "I completed the journal exercise you assigned.", time: "1 day ago", unread: false },
];
